title: EM Drives in Space
author: Don Wagner
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Em Drives are really cool. This blog exlpores the EM drive concept and 
  demonstrates how they work in space. Cool!

# social links
twitter_username: dlwagner
github_username:  dlwagner

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
